name = "AxisKeys"
uuid = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
license = "MIT"
version = "0.2.18"

[deps]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LazyStack = "1fad7336-0346-5a1a-a56f-a06ba010965b"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extensions]
AbstractFFTsExt = "AbstractFFTs"
ChainRulesCoreExt = "ChainRulesCore"
CovarianceEstimationExt = "CovarianceEstimation"
InterpolationsExt = "Interpolations"
InvertedIndicesExt = "InvertedIndices"
LazyStackExt = "LazyStack"
OffsetArraysExt = "OffsetArrays"
StatisticsExt = "Statistics"
StatsBaseExt = "StatsBase"

[compat]
AbstractFFTs = "1"
ChainRulesCore = "1"
CovarianceEstimation = "0.2"
Interpolations = "0.15"
IntervalSets = "0.7"
InvertedIndices = "1"
LazyStack = "0.0.7, 0.0.8"
LinearAlgebra = "1"
NamedDims = "1"
OffsetArrays = "1"
Statistics = "1"
StatsBase = "0.34"
Tables = "1"
julia = "1.10"
